## We are going to learn about Numpy and its basic methods

NumPy is a general-purpose array-processing package.
It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains among other things:

    * a powerful N-dimensional array object.
    * sophisticated (broadcasting) functions.
    * tools for integrating C/C++ and Fortran code.
    * useful linear algebra, Fourier transform, and random number
      capabilities.

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

### Arrays in NumPy

#### NumPy’s main object is the homogeneous multidimensional array.

    * It is a table of elements (usually numbers), all of the same type, 
      indexed by a tuple of positive integers.
    * In NumPy dimensions are called axes. The number of axes is rank.
    * NumPy’s array class is called ndarray. It is also known by the alias 
      array.

In [1]:
import numpy as np

# creating array object
a1 = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])
print(a1)

[[1 2 3]
 [4 2 5]]


In [2]:
# printing type of arr object
print("Array is of type: ", type(a1))

Array is of type:  <class 'numpy.ndarray'>


In [3]:
# printing array dimensions (axes)
print("No. of dimensions: ", a1.ndim)

No. of dimensions:  2


In [4]:
# printing shape of array
print("Shape of array: ", a1.shape)

Shape of array:  (2, 3)


In [5]:
# printing size (total number of elements) of array
print("Size of array: ", a1.size)

Size of array:  6


In [6]:
# printing type of elements in array
print("Array stores elements of type: ", a1.dtype)

Array stores elements of type:  int32


#### Array Creation

In [7]:
# creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [8]:
# creating array from tuple
b = np.array((1 , 3, 2))
print("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [9]:
# creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print("\nAn array initialized with all 6s. Array type is complex:\n", d)


An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [11]:
# create an array with random values
e = np.random.random((2,2))
print("\nA random array:\n", e)


A random array:
 [[0.43401567 0.90197521]
 [0.70080943 0.89347365]]


In [12]:
# create a sequence of integers from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [13]:
# create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print("\nA sequential array with 10 values between 0 and 5:\n", g)


A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [14]:
# reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print("\nOriginal array:\n", arr)
print("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [15]:
# flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print("\nOriginal array:\n", arr)
print("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


#### Array Indexing

In [16]:
a2 = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print(a2)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [17]:
# slicing
temp = a2[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [18]:
temp = a2[1:3, 1:4]
print("Array with 2nd and 3rd rows and alternate 2nd, 3rd and 4th columns:\n", temp)

Array with 2nd and 3rd rows and alternate 2nd, 3rd and 4th columns:
 [[-0.5  6.   0. ]
 [ 0.   7.   8. ]]


In [19]:
# integer array indexing example
temp = a2[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]


In [20]:
# boolean array indexing example
cond = a2 > 0    # cond is a boolean array
temp = a2[cond]
print("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


#### Basic Operations

In [21]:
a3 = np.array([1, 2, 5, 3])
print(a3)

[1 2 5 3]


In [22]:
# add 1 to every element
print("Adding 1 to every element:", a3+1)

Adding 1 to every element: [2 3 6 4]


In [23]:
# subtract 3 from each element
print("Subtracting 3 from each element:", a3-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [24]:
# multiply each element by 10
print("Multiplying each element by 10:", a3*10)

Multiplying each element by 10: [10 20 50 30]


In [25]:
# square each element
print("Squaring each element:", a3**2)

Squaring each element: [ 1  4 25  9]


In [26]:
# modify existing array
a3 *= 2
print("Doubled each element of original array:", a3)

Doubled each element of original array: [ 2  4 10  6]


In [27]:
# transpose of array 
a3 = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a3)
print("Transpose of array:\n", a3.T)


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [28]:
a4 = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])
print(a4)

[[1 5 6]
 [4 7 2]
 [3 1 9]]


In [29]:
# maximum element of array
print("Largest element is:", a4.max())
print("Row-wise maximum elements:", a4.max(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]


In [30]:
# minimum element of array
print("Column-wise minimum elements:", a4.min(axis = 0))

Column-wise minimum elements: [1 1 2]


In [31]:
# sum of array elements
print("Sum of all array elements:", a4.sum())

Sum of all array elements: 38


In [32]:
# cumulative sum along each row
print("Cumulative sum along each row:\n", a4.cumsum(axis = 1))

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [33]:
p = np.array([[1, 2], 
              [3, 4]])
q = np.array([[4, 3], 
              [2, 1]])
print(p, end="\n\n")
print(q)

[[1 2]
 [3 4]]

[[4 3]
 [2 1]]


In [34]:
# add arrays
print("Array sum:\n", p + q)

Array sum:
 [[5 5]
 [5 5]]


In [35]:
# multiply arrays (elementwise multiplication)
print("Array multiplication:\n", p*q)

Array multiplication:
 [[4 6]
 [6 4]]


In [36]:
# matrix multiplication
print("Matrix multiplication:\n", p.dot(q))

Matrix multiplication:
 [[ 8  5]
 [20 13]]


Universal functions (ufunc): NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

>Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [37]:
# create an array of sine values
a5 = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a5))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [38]:
# exponential values
a6 = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a6))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [39]:
# square root of array values
print("Square root of array elements:", np.sqrt(a6))

Square root of array elements: [0.         1.         1.41421356 1.73205081]


#### Sorting Array

In [40]:
x = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])
print(x)

[[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]


In [41]:
# sorted array
print("Array elements in sorted order:\n", np.sort(x, axis = None))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [42]:
# sort array row-wise
print("Row-wise sorted array:\n", np.sort(x, axis = 1))

Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [43]:
# specify sort algorithm
print("Column wise sort by applying merge-sort:\n", np.sort(x, axis = 0, kind = 'mergesort'))

Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [44]:
# example to show sorting of structured array
## set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
## values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
## creating array
y = np.array(values, dtype = dtypes)
print("\nArray sorted by names:\n", np.sort(y, order = 'name'))
print("Array sorted by grauation year and then cgpa:\n", np.sort(y, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


#### Stacking and Splitting

Several arrays can be stacked together along different axes.

>np.vstack: To stack arrays along vertical axis.

>np.hstack: To stack arrays along horizontal axis.

>np.column_stack: To stack 1-D arrays as columns into 2-D arrays.

>np.concatenate: To stack arrays along specified axis (axis is passed as argument).

In [45]:
m = np.array([[1, 2],
              [3, 4]])

n = np.array([[5, 6],
              [7, 8]])
print(m, end='\n\n')
print(n)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [46]:
# vertical stacking
print("Vertical stacking:\n", np.vstack((m, n)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
# horizontal stacking
print("\nHorizontal stacking:\n", np.hstack((m, n)))


Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [48]:
o = [5, 6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((m, o)))


Column stacking:
 [[1 2 5]
 [3 4 6]]


In [49]:
# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((m, n), 1))


Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


For splitting, we have these fuctions:

>np.hsplit: Split array along horizontal axis.

>np.vsplit: Split array along vertical axis.

>np.array_split: Split array along specified axis.

In [50]:
a7 = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

print(a7)

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


In [51]:
# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a7, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


In [52]:
# vertical splitting
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a7, 2))


Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


### Some More Numpy Functions - Statistics

>min, max, mean, median, average, variance, standard devidation

In [53]:
a8 = np.array([[1,2,3,4],[7,6,2,0]])
print(a8, end='\n\n')
print(np.min(a8), end='\n\n')
#Specify axis for the direction in case of multidim array
print(np.min(a8,axis=0), end='\n\n')
print(np.min(a8,axis=1), end='\n\n')

[[1 2 3 4]
 [7 6 2 0]]

0

[1 2 2 0]

[1 0]



In [54]:
a9 = np.array([1,2,3,4,5])
m = sum(a9)/5
print(m, end='\n\n')

print(np.mean(a9), end='\n\n')
print(np.mean(a8,axis=0), end='\n\n')
print(np.mean(a8,axis=1))

3.0

3.0

[4.  4.  2.5 2. ]

[2.5  3.75]


In [55]:
ar = np.array([1,5,4,2,0])
print(np.median(ar))

2.0


In [56]:
# Mean vs Average is Weighted
print(np.mean(ar))

2.4


In [57]:
# Weights 
w = np.array([1,1,1,1,1])
print(np.average(ar,weights=w))

# weighted mean => n1*w1 + n2*w2 / n1+n2

2.4


In [58]:
# Standard Deviation
u = np.mean(ar)
myStd = np.sqrt(np.mean(abs(ar-u)**2))
print(myStd)

1.854723699099141


In [59]:
#Inbuilt Function
dev= np.std(ar)
print(dev)

1.854723699099141


In [60]:
#Variance
print(myStd**2, end='\n\n')
print(np.var(ar))

3.440000000000001

3.4400000000000004


### Numpy Random Module

>rand : Random values in a given shape.

>randn : Return a sample (or samples) from the “standard normal”
distribution.

>randint : Return random integers from low (inclusive) to high (exclusive).

>random : Return random floats in the half-open interval [0.0, 1.0)

>choice : Generates a random sample from a given 1-D array

>Shuffle : Shuffles the contents of a sequence

In [61]:
a10 = np.arange(10) + 5
print(a10)

[ 5  6  7  8  9 10 11 12 13 14]


In [62]:
np.random.seed(1)
np.random.shuffle(a10)
print(a10)

[ 7 14 11  9  5  8  6 12 13 10]


In [63]:
#Returns values from a Standard Normal Distributions
a11 = np.random.randn(2,3)
print(a11)

[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]


In [64]:
a12 = np.random.randint(5,10,3)
print(a12)

[7 9 6]


In [65]:
#Randoly pick one element from an array
element = np.random.choice([1,4,3,2,11,27])
print(element)

4
