# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print('The numpy version is : ', np.__version__, end = '\n\n')      #or we can use np.version.version
print('The numpy configuration is : ', np.show_config())            #or we can use np.__config__.show() directly

The numpy version is :  1.18.1

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Prithvi Raj Karki/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Prithvi Raj Karki/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Prithvi Raj Karki/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\In

#### 3. Create a null vector of size 10

In [3]:
a1 = np.zeros(10, dtype=int)
print(a1)
print(type(a1))
print(a1.dtype)
print(a1.size)

[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>
int32
10


#### 4.  How to find the memory size of any array

In [4]:
print(a1)
print('Elements type :', a1.dtype)
print('Array size :', a1.size)
print('Elements size :',a1.itemsize)
print('Memory size of a1 :', a1.size*a1.itemsize,'bytes')

a2 = np.array([2.9, 2.4, 38, 12.4, 45.2])
print('\n', a2)
print('Elements type :', a2.dtype)
print('Array size :', a2.size)
print('Elements size :',a2.itemsize)
print('Memory size of a2 :', a2.size*a2.itemsize,'bytes')

a3 = np.array([2, 2.4, 38, 'abcd', 45.2])
print('\n', a3)
print('Elements type :', a3.dtype)
print('Array size :', a3.size)
print('Elements size :',a3.itemsize)
print('Memory size of a3 :', a3.size*a3.itemsize,'bytes')

[0 0 0 0 0 0 0 0 0 0]
Elements type : int32
Array size : 10
Elements size : 4
Memory size of a1 : 40 bytes

 [ 2.9  2.4 38.  12.4 45.2]
Elements type : float64
Array size : 5
Elements size : 8
Memory size of a2 : 40 bytes

 ['2' '2.4' '38' 'abcd' '45.2']
Elements type : <U32
Array size : 5
Elements size : 128
Memory size of a3 : 640 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
a4 = np.zeros(10, dtype=int)
a4[4] = 1
print(a4)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
print('The vector is :', a3)
print('\nAnd Reverse of the vector is :', a3[::-1])

The vector is : ['2' '2.4' '38' 'abcd' '45.2']

And Reverse of the vector is : ['45.2' 'abcd' '38' '2.4' '2']


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a5 = np.arange(0,9).reshape(3,3)
print(a5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [10]:
a6 = np.array([1, 2, 0, 0, 4, 0])
print("Indices of non-zero elements are :\n", a6.nonzero())
print("And the corresponding non-zero elements are :\n", a6[a6.nonzero()])

Indices of non-zero elements are :
 (array([0, 1, 4], dtype=int64),)
And the corresponding non-zero elements are :
 [1 2 4]


#### 11. Create a 3x3 identity matrix

In [11]:
a7 = np.identity(3)    #Or np.eye(3)
print(a7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [12]:
a8 = np.random.random((3,3,3))
print(a8)

[[[0.53354604 0.10030077 0.17017992]
  [0.33505182 0.38310842 0.20666341]
  [0.73781488 0.99722752 0.04062966]]

 [[0.8680002  0.34521939 0.99026277]
  [0.9248335  0.92649928 0.4729673 ]
  [0.8075973  0.67105286 0.67407801]]

 [[0.92376041 0.62408656 0.35252636]
  [0.40230066 0.99660155 0.12975573]
  [0.57901726 0.87431673 0.70197589]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
a9 = np.random.random((10,10))
print('The array is :\n', a9)
print('\nThe maximum value is %f and minimum value is %f in the array:' %(a9.max(), a9.min()))

The array is :
 [[0.22484822 0.75679048 0.51222275 0.70341462 0.32089933 0.62592552
  0.90588699 0.65188044 0.12306746 0.47510997]
 [0.97764807 0.52904379 0.17398211 0.2865718  0.75671819 0.78384876
  0.68328498 0.18343176 0.79924786 0.46813619]
 [0.5552548  0.08889537 0.47858216 0.10328716 0.50634023 0.23481093
  0.02050519 0.62525395 0.70915326 0.76205494]
 [0.3896061  0.99963103 0.66566686 0.04424334 0.21867789 0.46047321
  0.31391619 0.21044609 0.75574657 0.2151877 ]
 [0.72498843 0.43774067 0.93160715 0.47759829 0.72626213 0.08647282
  0.7585568  0.50463171 0.08085059 0.2736838 ]
 [0.33293074 0.64763165 0.20547543 0.60081473 0.29754202 0.27887654
  0.59177202 0.2042889  0.12098601 0.70181934]
 [0.01187766 0.32383593 0.65226573 0.29751914 0.16840926 0.58681641
  0.87047836 0.36459653 0.36891914 0.84759503]
 [0.27791235 0.35687072 0.40054457 0.74309097 0.13876582 0.90485339
  0.68192666 0.58036599 0.93531394 0.54318057]
 [0.29490354 0.52782689 0.15578748 0.93057041 0.22668111 0.00820

#### 14. Create a random vector of size 30 and find the mean value

In [14]:
arr1 = np.random.random(30)
print(arr1)
print('\nThe mean of the elements of the array :', arr1.mean())

[0.86728907 0.35961756 0.63194526 0.19579444 0.74096275 0.38875654
 0.04812687 0.37927845 0.04807382 0.31089815 0.26403909 0.16554304
 0.76865453 0.51202272 0.82196529 0.07250532 0.82876809 0.30755268
 0.78025584 0.556691   0.36400631 0.86780791 0.27319029 0.98822845
 0.90755879 0.68245582 0.61925102 0.58088535 0.61849063 0.90963845]

The mean of the elements of the array : 0.5286751161990435


#### 15. Create a 2d array with 1 on the border and 0 inside

In [15]:
arr2 = np.ones((6,7))
arr2[1:-1,1:-1] = 0
print(arr2)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [16]:
print('We are having an existing array :\n', a5)
temp = np.zeros(tuple(np.array(a5.shape) + 2), dtype=int)
temp[1:-1, 1:-1] = a5
print('\nNow, after adding border filled with 0\'s :\n', temp)

We are having an existing array :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Now, after adding border filled with 0's :
 [[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
arr3 = np.diag(1 + np.arange(4), k = -1)
print(arr3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
arr4 = np.zeros((8,8), dtype=int)
arr4[1::2, ::2] = 1
arr4[::2, 1::2] = 1
print(arr4)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)
